name: Java

on:
  push:
    branches: [ "main" ]
    paths: [ "**/java/**" ]
  pull_request:
    branches: [ "main" ]
    paths: [ "**/java/**" ]

jobs:
  linked_list_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Linked List Tests
        run: |
          cd data_structures/linked_lists/java
          mvn test
  
  queue_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Queue Tests
        run: |
          cd data_structures/queues/java
          mvn test

  stack_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Stack Tests
        run: |
          cd data_structures/stacks/java
          mvn test
